### PR TITLE
451 - Add structured input fields for tasks requiring human input

### PR DESCRIPTION
**Pull request by iandjx**
### **User description**
solves  #451 To implement structured input fields in tasks with human input

___

### **PR Type**
Enhancement

___

### **Description**
- Added new API function `getTaskByName` to fetch tasks by name.
- Created `DraggableSortableItem`, `FormConfig`, and `SortableItem` components for form field management.
- Integrated `FormConfig` into `TaskForm` and updated form submission to include form fields.
- Created `StructuredInputForm` component for structured human input with validation.
- Added `taskByName` controller and updated `addTaskApi` and `editTaskApi` to handle form fields.
- Added `getTaskByName` function in the task database module.
- Created `useActiveTask` hook to fetch the active task based on messages.
- Added `FormFieldConfig` interface and updated `Task` interface to include form fields.
- Integrated `StructuredInputForm` into the session page.
- Added route for fetching task by name.
- Added dependencies for `@dnd-kit` packages.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><details><summary>13 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>api.ts</strong><dd><code>Add API function to fetch tasks by name.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

webapp/src/api.ts
<li>Added <code>getTaskByName</code> function to fetch tasks by name.<br> <li> Updated imports to include <code>GetTaskByNameDispatch</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/456/files#diff-f4089702dd4146c64bdf8ded4132e0aa103545928d504520644aa1fa54bccae5">+12/-1</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>DraggableSortableItem.tsx</strong><dd><code>Create DraggableSortableItem component for form fields.</code>&nbsp; &nbsp; </dd></summary>
<hr>

webapp/src/components/DraggableSortableItem.tsx
<li>Created <code>DraggableSortableItem</code> component for draggable form fields.<br> <li> Utilized <code>useSortable</code> from <code>@dnd-kit/sortable</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/456/files#diff-7d0833c4a9017366dd605e49ed31a6867a76e0d0f86540b8726f00e2cb2558d5">+44/-0</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>FormConfig.tsx</strong><dd><code>Create FormConfig component with drag-and-drop functionality.</code></dd></summary>
<hr>

webapp/src/components/FormConfig.tsx
<li>Created <code>FormConfig</code> component for configuring form fields.<br> <li> Implemented drag-and-drop functionality using <code>@dnd-kit</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/456/files#diff-59a4523c428124d92a411e0d3b50255b6dd89d5e4b8432a039370d449ecdcce6">+121/-0</a>&nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>SortableItem.tsx</strong><dd><code>Create SortableItem component for form fields.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

webapp/src/components/SortableItem.tsx
<li>Created <code>SortableItem</code> component for individual form fields.<br> <li> Added functionality to edit, delete, and reorder form fields.<br>

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/456/files#diff-3456bb407931e70cbe8368c2fa4d7c3d3ca684a7860c6911d354f4e56798b0d9">+246/-0</a>&nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>TaskForm.tsx</strong><dd><code>Integrate FormConfig into TaskForm and update submission.</code></dd></summary>
<hr>

webapp/src/components/TaskForm.tsx
<li>Integrated <code>FormConfig</code> component into <code>TaskForm</code>.<br> <li> Updated form submission to include form fields.<br>

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/456/files#diff-21f2207d9c819f01aef6612d3cc678ec0075e1653a5550ea6bd8ff62a2dc31fa">+36/-21</a>&nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>StructuredInputForm.tsx</strong><dd><code>Create StructuredInputForm component for human input.</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

webapp/src/components/session/StructuredInputForm.tsx
<li>Created <code>StructuredInputForm</code> component for structured human input.<br> <li> Added form validation and error handling.<br>

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/456/files#diff-08b9c019ee6f0a8613c71e48ba7202a0b90579df1b008a1286db9209c616ba8c">+231/-0</a>&nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>task.ts</strong><dd><code>Add taskByName controller and update task APIs.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

webapp/src/controllers/task.ts
<li>Added <code>taskByName</code> controller to fetch tasks by name.<br> <li> Updated <code>addTaskApi</code> and <code>editTaskApi</code> to handle form fields.<br>

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/456/files#diff-65b58c8dea9a60912e31738bd67047363d6ebf24ab188420b90e48c7e1a0b06e">+73/-6</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>task.ts</strong><dd><code>Add getTaskByName function in task database module.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

webapp/src/db/task.ts
<li>Added <code>getTaskByName</code> function to fetch tasks by name from the database.<br> <br>

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/456/files#diff-8d443451516c4bf63f41fd17aa301861059419f4179f5a7b651b33797a602ab1">+7/-0</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>useActiveTask.ts</strong><dd><code>Create useActiveTask hook to fetch active task.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

webapp/src/hooks/session/useActiveTask.ts
<li>Created <code>useActiveTask</code> hook to fetch the active task based on messages.<br> <br>

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/456/files#diff-a8cf6ccaa8ba6a884424255229e10f77d5126ada21710d78b26450dee47d1f9c">+41/-0</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>dispatchtypes.ts</strong><dd><code>Add GetTaskByNameDispatch type.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

webapp/src/lib/struct/dispatchtypes.ts
<li>Added <code>GetTaskByNameDispatch</code> type for dispatching task fetch by name.<br>

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/456/files#diff-45350a7df1ec8f2d4e2e1a3fbe6b598c62620fab934cb0a4c17cd6590a0e791c">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>task.ts</strong><dd><code>Add FormFieldConfig interface and update Task interface.</code>&nbsp; </dd></summary>
<hr>

webapp/src/lib/struct/task.ts
<li>Added <code>FormFieldConfig</code> interface for form field configuration.<br> <li> Updated <code>Task</code> interface to include form fields.<br>

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/456/files#diff-0e8baeb5d9b20beca9bb97a8fc5dd120a335f23d0787581ab8db1dcc84d16fa8">+12/-0</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>index.tsx</strong><dd><code>Integrate StructuredInputForm into session page.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

webapp/src/pages/[resourceSlug]/session/[sessionId]/index.tsx
<li>Integrated <code>StructuredInputForm</code> into session page.<br> <li> Displayed structured input form based on active task.<br>

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/456/files#diff-08ec8d1386812576d41c7726d452be5b96bcc8cc4e335f133431b5ce6dae65e7">+31/-24</a>&nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>router.ts</strong><dd><code>Add route for fetching task by name.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

webapp/src/router.ts
- Added route to fetch task by name.

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/456/files#diff-06d18801adea660fe16b11a269b89605adc1c57efc96c57664203c450129435e">+4/-0</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></details></td></tr><tr><td><strong>Dependencies
</strong></td><td><details><summary>2 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>package-lock.json</strong><dd><code>Add @dnd-kit dependencies.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

webapp/package-lock.json
- Added dependencies for `@dnd-kit` packages.

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/456/files#diff-f343c123f7a6f32c9db380cf4fc71b466adcd784e994457df19f516fbea98c5a">+65/-0</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>package.json</strong><dd><code>Add @dnd-kit dependencies.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

webapp/package.json
- Added dependencies for `@dnd-kit` packages.

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/456/files#diff-006cce2fd88392a0bff4cf16091d480b6238c6bdf52c9042bf7805879c791a8f">+3/-0</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by iandjx** [comment]
Preparing PR description...

**Comment by iandjx** [comment]
**[PR Description](https://github.com/rnadigital/agentcloud/pull/456)** updated to latest commit (https://github.com/rnadigital/agentcloud/commit/6aff2442e853c7860e77e7f42588ac4fa9e5deec)

**Comment by iandjx** [comment]
Preparing PR description...

**Comment by iandjx** [comment]
**[PR Description](https://github.com/rnadigital/agentcloud/pull/456)** updated to latest commit (https://github.com/rnadigital/agentcloud/commit/6aff2442e853c7860e77e7f42588ac4fa9e5deec)

**Comment by tomlynchRNA** [comment]
reviewing now, apologies for my tardiness :slightly_smiling_face:

**Comment by tomlynchRNA** [comment]
:rocket: lgtm

**Pull request merged**
