### PR TITLE
461 structured output

### PR DESCRIPTION
**Pull request by iandjx**
### **PR Type**
enhancement, bug fix

___

### **Description**
- Added JSON validation for structured output schema in `ScriptEditor`.
- Introduced structured output toggle and JSON editor in `TaskForm`.
- Improved message handling for JSON content in chat and socket communication.
- Added `isStructuredOutput` handling in task creation and editing APIs.
- Created utility for converting JSON schema to Pydantic model.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><details><summary>8 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>Editor.tsx</strong><dd><code>Add JSON validation and language prop to ScriptEditor</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

webapp/src/components/Editor.tsx
<li>Added JSON validation for structured output schema.<br> <li> Introduced <code>language</code> prop to <code>ScriptEditorProps</code>.<br> <li> Updated <code>ScriptEditor</code> component to handle JSON schema validation.<br>

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/471/files#diff-79325d3e3791b750045fc4ec111cd94fb72456b725a6bdd2a986396249049ad4">+83/-4</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>TaskForm.tsx</strong><dd><code>Add structured output toggle and JSON editor</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

webapp/src/components/TaskForm.tsx
<li>Added structured output toggle and JSON editor.<br> <li> Updated state management for <code>expectedOutput</code> and <code>isStructuredOutput</code>.<br> <li> Integrated <code>ScriptEditor</code> for structured output.<br>

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/471/files#diff-21f2207d9c819f01aef6612d3cc678ec0075e1653a5550ea6bd8ff62a2dc31fa">+106/-18</a></td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>task.ts</strong><dd><code>Add isStructuredOutput handling in task API</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

webapp/src/controllers/task.ts
- Added `isStructuredOutput` handling in task creation and editing.

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/471/files#diff-65b58c8dea9a60912e31738bd67047363d6ebf24ab188420b90e48c7e1a0b06e">+8/-4</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>task.ts</strong><dd><code>Add isStructuredOutput field to Task interface</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

webapp/src/lib/struct/task.ts
- Added `isStructuredOutput` field to `Task` interface.

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/471/files#diff-0e8baeb5d9b20beca9bb97a8fc5dd120a335f23d0787581ab8db1dcc84d16fa8">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>add.tsx</strong><dd><code>Adjust layout for task form</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

webapp/src/pages/[resourceSlug]/task/add.tsx
- Adjusted layout for task form.

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/471/files#diff-9dce471d9c9ce31c9f05ac5a5fb4ee441514c12b035dd9185f547ca97fcad115">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>build_crew.py</strong><dd><code>Add JSON schema to Pydantic conversion for structured output</code></dd></summary>
<hr>

agent-backend/src/crew/build_crew.py
<li>Added JSON schema to Pydantic model conversion for structured output.<br> <li> Handled structured output in task building.<br>

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/471/files#diff-054e616b56655751577957faedbec2ee373994d6b8b45fdded6d63a275e1fb8c">+12/-2</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>mongo.py</strong><dd><code>Add isStructuredOutput field to Task model</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

agent-backend/src/models/mongo.py
- Added `isStructuredOutput` field to `Task` model.

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/471/files#diff-77a9c1c61d79d878884f42670de8fc79ce47bb8cf8bfdd78fac23cbe1acef432">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>json_schema_to_pydantic.py</strong><dd><code>Create utility for JSON schema to Pydantic conversion</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

agent-backend/src/utils/json_schema_to_pydantic.py
- Created utility for converting JSON schema to Pydantic model.

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/471/files#diff-8b0c4b0cec0cd67259e6f146a962eefe7d88fa25b570d3064fb4fdf438fad57b">+40/-0</a>&nbsp; &nbsp; </td>
</tr>                    
</table></details></td></tr><tr><td><strong>Bug fix
</strong></td><td><details><summary>3 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>message.tsx</strong><dd><code>Improve message handling for JSON content</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

webapp/src/components/chat/message.tsx
<li>Improved message handling for JSON content.<br> <li> Ensured proper message formatting for code blocks.<br>

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/471/files#diff-db0cbe0afca6fcbdeb236ec541e480878b93476682a652ada597cad1b605ed42">+5/-2</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>add.tsx</strong><dd><code>Add null check for tools array</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

webapp/src/pages/[resourceSlug]/tool/add.tsx
- Added null check for tools array.

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/471/files#diff-f058cd447c95571de7bc5a9886cc3553a7d45b161291212cee3879846f498024">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>socketio.ts</strong><dd><code>Improve JSON message handling in socket communication</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

webapp/src/socketio.ts
<li>Improved message handling for JSON content in socket communication.<br>

</details>
    

  </td>
  <td><a href="https://github.com/rnadigital/agentcloud/pull/471/files#diff-2c21fc4ba335348cb2cfefc0bd68213ea0610d082de4f5b8baa5c9458c8b60a4">+16/-23</a>&nbsp; </td>
</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by iandjx** [comment]
Preparing review...

**Comment by iandjx** [comment]
## PR Review 🔍

<table>
<tr>
<tr><td> ⏱️&nbsp;<strong>Estimated&nbsp;effort&nbsp;to&nbsp;review [1-5]</strong></td><td>

3, because the PR involves multiple files with significant changes including TypeScript and Python, affecting both frontend and backend components. The changes include adding new features and modifying existing functionalities which require careful review to ensure compatibility and correctness.


</td></tr>
<tr><td> 🧪&nbsp;<strong>Relevant tests</strong></td><td>

No


</td></tr>
<tr><td rowspan=2> ⚡&nbsp;<strong>Possible issues</strong></td>
<td>

<strong>Possible Bug:</strong> The use of `any` type in TypeScript can lead to potential type safety issues. For example, `const monacoEditorRef = useRef<any | null>(null);` could be more type-safe.</td></tr>
<tr>
<td>

<strong>Performance Concern:</strong> The JSON schema validation setup in `Editor.tsx` might be computationally expensive if triggered frequently.</td></tr>
<tr><td> 🔒&nbsp;<strong>Security concerns</strong></td><td>

No

</td></tr>
</table>


<details><summary> <strong>Code feedback:</strong></summary>

<hr><table><tr><td>relevant file</td><td>webapp/src/components/Editor.tsx
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Consider using a more specific type instead of `any` for `editorRef` and `monacoEditorRef`. This will improve type safety and help catch errors during compilation. For example, you could define interfaces for the editor and monaco objects. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/rnadigital/agentcloud/pull/471/files#diff-79325d3e3791b750045fc4ec111cd94fb72456b725a6bdd2a986396249049ad4R46'>const monacoEditorRef = useRef<typeof monaco.editor>(null);</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>webapp/src/components/TaskForm.tsx
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

It's a good practice to handle potential errors in JSON parsing operations. Consider adding a try-catch block around the JSON.parse call in the `useEffect` hook to handle malformed JSON input gracefully. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/rnadigital/agentcloud/pull/471/files#diff-21f2207d9c819f01aef6612d3cc678ec0075e1653a5550ea6bd8ff62a2dc31faR243'>setExpectedOutput(jsonPlaceholder);</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>agent-backend/src/crew/build_crew.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

To ensure that the `json.loads` function does not raise an exception when invalid JSON is provided, wrap this call in a try-except block. Handle the exception appropriately, possibly logging an error or setting a default value. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/rnadigital/agentcloud/pull/471/files#diff-054e616b56655751577957faedbec2ee373994d6b8b45fdded6d63a275e1fb8cR171'>task_model = json_schema_to_pydantic(json.loads(task.expectedOutput))</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>webapp/src/components/Editor.tsx
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

To enhance the user experience and reduce errors, consider adding a fallback or default schema if the fetch from 'https://agent-cloud/schemas/output-schema.json' fails or is unavailable. This can be done by catching errors in the schema fetching process and using a predefined default schema. [medium]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/rnadigital/agentcloud/pull/471/files#diff-79325d3e3791b750045fc4ec111cd94fb72456b725a6bdd2a986396249049ad4R77'>uri: 'https://agent-cloud/schemas/output-schema.json',</a></td></tr></table><hr>

</details>

**Comment by iandjx** [comment]
Preparing PR description...

**Comment by iandjx** [comment]
**[PR Description](https://github.com/rnadigital/agentcloud/pull/471)** updated to latest commit (https://github.com/rnadigital/agentcloud/commit/1c86e56cc60544154d16cb114ea1d5a4d19d5c88)

**Comment by iandjx** [comment]
@CodiumAI-Agent /describe

**Comment by iandjx** [comment]
@CodiumAI-Agent /describe

**Review by tomlynchRNA — APPROVED** [review]

**Pull request merged**
